// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToe.Dal;

#nullable disable

namespace TicTacToe.Dal.Migrations
{
    [DbContext(typeof(TicTacToeContext))]
    [Migration("20211118122455_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TicTacToe.Domain.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Cells")
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("CrossId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("NextTurn")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Winner")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ZeroId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("TicTacToe.Domain.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
